### ISSUE TITLE
Allow semantical message values to be set

### ISSUE THREAD

**Issue by adriansmares** [TheThingsIndustries/protoc-gen-go-flags#14]
#### Summary

Some messages (generally `oneof` fields) may have a semantic meaning only by their presence (i.e. being non empty). Such messages should get `set` flags if explicitly requested.

#### Why do we need this?

The main use case here is the ADR mode API at https://github.com/TheThingsNetwork/lorawan-stack/blob/943d83e7deb383027b208e96752adcbaf5c27757/api/end_device.proto#L186-L237

The `disabled` message is empty, but simply by being present it produces effects. At the moment `disabled` cannot be set via the generated `set` flags since we produce `set` flags only for non-message leaves.

#### What is already there? What do you see now?

`set` flags for non-message fields.

#### What is missing? What do you want to see?

`set` flags for message fields when explicitly requested via options.

#### How do you propose to implement this?

@htdvisser do you have some pointers for me on how to do this one ?

#### How do you propose to test this?

Regenerate the flags for the ADR settings.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by htdvisser** [comment]
Okay yeah, so I can indeed imagine this could be useful for the specific situation of a message with zero fields that's used in a oneof, but strictly speaking, this distinction can be made for any message, also messages that are not in a oneof.

So I think we have two choices:

1. Add a (hidden) boolean flag for each "message" field that just initializes an empty message.
2. Add a (also hidden) flag for each message field that accepts the entire field as JSON.

I think it's obvious that (1) is less work, but at the same time, I can imagine that we may _want_ to do (2) in the future.

**Comment by adriansmares** [comment]
I think that (2) comes with unexpected semantics (what field mask do you use ? you may be tempted to say that we replace the whole message, but this may not be what users expect) and extra complexity (this would probably tie this particular plugin with the JSON generation one), so I'm inclined to go for (1) and require that full message updates are done using the subfields + `--unset`.
